#!/usr/bin/ruby

STDERR.print <<EOS
Warning: The Ruby Homebrew uninstaller is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://gitee.com/yao2019ss/install/blob/master/uninstall.sh)"

EOS

Kernel.exec "/bin/bash", "-c", '/bin/bash -c "$(curl -fsSL https://gitee.com/yao2019ss/install/blob/master/uninstall.sh)"' + ' uninstall ' +  ARGV.join(" ")
